@extends('layouts.admin.default')

@section('title', 'Placement Tests')

{{-- @include('layouts.css_and_js.form_general') --}}

{{-- @include('layouts.css_and_js.calendar') --}}

@include('layouts.css_and_js.table')

@section('content-header')
  <h1><b>Student Placement Tests</b></h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}">Home</a></li>
    <li class="active">Placement Tests</li>
  </ol>
@stop

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#all_submissions" data-toggle="tab"><b>All Submissions</b></a></li>
          @foreach($material_types as $mt)
            <li><a href="#sub_type{{ $mt->id }}" data-toggle="tab"><b>{{ $mt->name }}</b></a></li>
          @endforeach
        </ul>
        <div class="tab-content">
          <div class="active tab-pane" id="all_submissions">
            <div class="row">
              <div class="col-md-3">
                <div class="box">
                  {{--
                  <div class="box-header">
                    <h3 class="box-title">Section Title</h3>
                  </div>
                  --}}
                  <div class="box-body">
                    <dl>
                      <dt style="font-size:18px;"><i class="fa fa-file-video-o margin-r-5"></i> Viewing the Result</dt>
                      <dd>
                        Click "view" button to check the test result from each student!<br />
                      </dd>
                    </dl>
                    <hr>
                    <dl>
                      <dt style="font-size:18px;"><i class="fa fa-file-text-o margin-r-5"></i> More Information</dt>
                      <dd>
                        Click "detail" button to show more information from each submission. Changing the proficiency level of each student can only be done from a page generated by this button.<br />
                        <span style="color:#ff0000;">* Contact us if you encounter a problem.</span>
                      </dd>
                    </dl>
                    {{-- <hr> --}}
                  </div>
                </div>
              </div>
              <div class="col-md-9 no-padding">
                <div class="col-md-12">
                  <div class="box box-primary">
                    <div class="box-header">
                      <h3 class="box-title"><b>All Submissions</b></h3>
                      <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" aria-label="Minimize"><i class="fa fa-minus"></i></button>
                      </div>
                    </div>
                    <div class="box-body">
                      @if($placement_tests->toArray() != null)
                        <table class="table table-bordered">
                          <tr>
                            <th>Material / Proficiency</th>
                            <th>Student Name</th>
                            <th style="width:5%;">View</th>
                            <th style="width:5%;">Detail</th>
                          </tr>
                          @foreach($placement_tests as $dt)
                            <tr>
                              <td>{{ $dt->course_registration->course->course_package->material_type->name }} / {{ $dt->course_registration->student->indonesian_language_proficiency }}</td>
                              <td>{{ $dt->course_registration->student->user->first_name }} {{ $dt->course_registration->student->user->last_name }}</td>
                              <td>
                                <a target="_blank" rel="noopener noreferrer" class="btn btn-flat btn-xs btn-success" href="{{ $dt->path }}">View</a>
                              </td>
                              <td class="text-center">
                                <a target="_blank" rel="noopener noreferrer" class="btn btn-flat btn-xs bg-blue" href="{{ route('placement_tests.show', [$dt->id]) }}">Detail</a>
                              </td>
                            </tr>
                          @endforeach
                        </table>
                      @else
                        <div class="text-center">No data available.</div>
                      @endif
                    </div>
                    <!-- /.box-body -->
                  </div>
                  <!-- /.box -->
                </div>
              </div>
            </div>
          </div>
          <!-- /.tab-pane -->
          @foreach($material_types as $mt)
            <div class="tab-pane" id="sub_type{{ $mt->id }}">
              <div class="row">
                <div class="col-md-3">
                  <div class="box">
                    {{--
                    <div class="box-header">
                      <h3 class="box-title">Section Title</h3>
                    </div>
                    --}}
                    <div class="box-body">
                      <dl>
                        <dt style="font-size:18px;"><i class="fa fa-file-video-o margin-r-5"></i> Viewing the Result</dt>
                        <dd>
                          Click "view" button to check the test result from each student!<br />
                        </dd>
                      </dl>
                      <hr>
                      <dl>
                        <dt style="font-size:18px;"><i class="fa fa-file-text-o margin-r-5"></i> More Information</dt>
                        <dd>
                          Click "detail" button to show more information from each submission. Changing the proficiency level of each student can only be done from a page generated by this button.<br />
                          <span style="color:#ff0000;">* Contact us if you encounter a problem.</span>
                        </dd>
                      </dl>
                      {{-- <hr> --}}
                    </div>
                  </div>
                </div>
                <div class="col-md-9">
                  <div class="box box-primary">
                    <div class="box-header">
                      <h3 class="box-title"><b>{{ $mt->name }}</b></h3>
                      <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" aria-label="Minimize"><i class="fa fa-minus"></i></button>
                      </div>
                    </div>
                    <div class="box-body">
                      <?php
                        $flag = 0;
                        foreach($placement_tests as $i => $dt)
                          if($dt->course_registration->course->course_package->material_type_id == $mt->id) {
                            $flag = 1;
                            break;
                          }
                      ?>
                      @if($flag)
                        <table class="table table-bordered">
                          <tr>
                            <th>Proficiency</th>
                            <th>Student Name</th>
                            <th style="width:5%;">View</th>
                            <th style="width:5%;">Detail</th>
                          </tr>
                          @foreach($placement_tests as $dt)
                            @if($dt->course_registration->course->course_package->material_type_id == $mt->id)
                              <tr>
                                <td>{{ $dt->course_registration->student->indonesian_language_proficiency }}</td>
                                <td>{{ $dt->course_registration->student->user->first_name }} {{ $dt->course_registration->student->user->last_name }}</td>
                                <td>
                                  <a target="_blank" rel="noopener noreferrer" class="btn btn-flat btn-xs btn-success" href="{{ $dt->path }}">View</a>
                                </td>
                                <td class="text-center">
                                  <a target="_blank" rel="noopener noreferrer" class="btn btn-flat btn-xs bg-blue" href="{{ route('placement_tests.show', [$dt->id]) }}">Detail</a>
                                </td>
                              </tr>
                            @endif
                          @endforeach
                        </table>
                      @else
                        <div class="text-center">No data available.</div>
                      @endif
                    </div>
                    <!-- /.box-body -->
                  </div>
                  <!-- /.box -->
                </div>
              </div>
            </div>
            <!-- /.tab-pane -->
          @endforeach
        </div>
        <!-- /.tab-content -->
      </div>
      <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
  </div>
@stop
